use anyhow::{Result, Context};
use std::fs;
use std::path::Path;

pub fn run(name: &str) -> Result<()> {
    println!("Creating Zelto app: {name}");

    let root = Path::new(name);
    if root.exists() {
        anyhow::bail!("Directory '{name}' already exists");
    }

    fs::create_dir_all(root.join("src"))?;

    // zelto.toml
    fs::write(
        root.join("zelto.toml"),
        format!(
            r#"[app]
name = "{name}"
version = "0.1.0"
"#
        ),
    ).context("write zelto.toml")?;

    // Cargo.toml
    fs::write(
        root.join("Cargo.toml"),
        format!(
            r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "{name}"
path = "src/main.rs"

[dependencies]
zelto-runtime = {{ git = "https://github.com/zelto-framework/zelto" }}
zelto-std = {{ git = "https://github.com/zelto-framework/zelto" }}
zelto-ir = {{ git = "https://github.com/zelto-framework/zelto" }}
"#
        ),
    ).context("write Cargo.toml")?;

    // src/main.zelto (the user's TSX entry point)
    fs::write(
        root.join("src").join("main.zelto"),
        r#"import { useState } from "zelto";

function App() {
  const [count, setCount] = useState(0);

  return (
    <Window title="My Zelto App" width={400} height={300}>
      <View style={{ flexDirection: "column", padding: 20, gap: 12 }}>
        <Text>{count}</Text>
        <Button onClick={() => setCount(count + 1)}>Click me</Button>
      </View>
    </Window>
  );
}

export default App;
"#,
    ).context("write src/main.zelto")?;

    // src/main.rs — Rust entry that will be generated by compiler (Phase 2)
    // For Phase 1, devs write Rust directly using zelto-std builders
    fs::write(
        root.join("src").join("main.rs"),
        format!(
            r#"// Generated by `zelto new` — Phase 1 (Rust API).
// In Phase 2 this file will be auto-generated from src/main.zelto.
use zelto_runtime::{{App, AppConfig}};
use zelto_std::components::*;
use zelto_ir::ZeltoNode;

fn app() -> ZeltoNode {{
    view()
        .column()
        .padding(20.0)
        .gap(12.0)
        .child(text("Hello from {name}!"))
        .child(button("Click me").build())
        .build()
}}

fn main() {{
    App::new(
        AppConfig {{
            title: "{name}".into(),
            width: 400,
            height: 300,
            resizable: true,
        }},
        app,
    )
    .run()
    .unwrap();
}}
"#
        ),
    ).context("write src/main.rs")?;

    println!("Done! Run:");
    println!("  cd {name}");
    println!("  cargo run");

    Ok(())
}
